import YulIR.Ast
import YulIR.Effects
import YulIR.OfYul
import YulIR.ToYul
import YulIR.Object
import YulIR.Optimize
import YulIR.Frame
import YulIR.FrameTranslate
import YulIR.FrameSem
import YulIR.FrameBigStep
import YulIR.FrameSound
import YulIR.FrameFunCongr
import YulIR.FrameCongr
import YulIR.FramePasses
import YulIR.FrameOptimize
import YulIR.FrameStructuralSound
import YulIR.FrameDropSound
import YulIR.FrameSimplifySound
import YulIR.FrameDceSound
set_option warningAsError true
