/*
 * yulc.c - C shim between the public yulc.h interface and the Lean-compiled
 * compiler library.
 *
 * Responsibilities:
 *  - initialize the Lean runtime and the YulCApi module exactly once;
 *  - convert C strings/buffers to and from Lean objects;
 *  - run every call into Lean on a dedicated worker thread with a large
 *    stack, because compiling large real-world contracts recurses deeply
 *    (the in-repo native tools run under `ulimit -s unlimited` for the same
 *    reason) and because callers' threads must not be required to be Lean
 *    threads.
 *
 * The Lean-side entry points are the @[export] wrappers in YulCApi.lean.
 */
#include "include/yulc.h"

#include <limits.h>
#include <pthread.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

#include <lean/lean.h>

/* Lean runtime entry points not declared in <lean/lean.h> (see the upstream
 * reverse-ffi example, which declares them the same way). */
extern void lean_initialize_runtime_module(void);
extern void lean_initialize_thread(void);
extern void lean_finalize_thread(void);

/* Exported by YulCApi.lean. Both consume their String argument. */
extern lean_obj_res yulc_lean_compile(lean_obj_arg source);
extern uint8_t yulc_lean_parses(lean_obj_arg source);
/* Module initializer generated by Lean; transitively initializes imports.
 * The symbol carries the Lake package name ("yul-evm-compiler", with '-'
 * mangled to _x2d) as a prefix. */
extern lean_obj_res initialize_yul_x2devm_x2dcompiler_YulCApi(
    uint8_t builtin, lean_obj_arg w);

/* ---------------------------------------------------------------------- */
/* Big-stack worker threads                                                */

#define YULC_DEFAULT_STACK_BYTES ((size_t)1 << 30) /* 1 GiB, lazily committed */

static size_t worker_stack_bytes(void) {
  const char *env = getenv("YULC_STACK_BYTES");
  if (env && *env) {
    char *end = NULL;
    unsigned long long v = strtoull(env, &end, 10);
    if (end && *end == '\0' && v > 0 && v <= SIZE_MAX)
      return (size_t)v;
  }
  return YULC_DEFAULT_STACK_BYTES;
}

/* Run fn(arg) on a fresh thread with a large stack and wait for it.
 * Returns 0 on success, YULC_ERROR_INTERNAL if the thread could not be
 * created or joined. */
static int run_on_big_stack(void *(*fn)(void *), void *arg) {
  pthread_attr_t attr;
  if (pthread_attr_init(&attr) != 0)
    return YULC_ERROR_INTERNAL;
  size_t stack = worker_stack_bytes();
#ifdef PTHREAD_STACK_MIN
  if (stack < (size_t)PTHREAD_STACK_MIN)
    stack = (size_t)PTHREAD_STACK_MIN;
#endif
  /* Round up to the page size, as pthread_attr_setstacksize requires on
   * some systems. */
  long page = sysconf(_SC_PAGESIZE);
  if (page > 0)
    stack = (stack + (size_t)page - 1) & ~((size_t)page - 1);
  int rc = pthread_attr_setstacksize(&attr, stack);
  pthread_t thread;
  if (rc == 0)
    rc = pthread_create(&thread, &attr, fn, arg);
  if (rc != 0 && stack > YULC_DEFAULT_STACK_BYTES) {
    /* An oversized YULC_STACK_BYTES request may exceed available address
     * space; retry once with the default. */
    if (pthread_attr_setstacksize(&attr, YULC_DEFAULT_STACK_BYTES) == 0)
      rc = pthread_create(&thread, &attr, fn, arg);
  }
  pthread_attr_destroy(&attr);
  if (rc != 0)
    return YULC_ERROR_INTERNAL;
  if (pthread_join(thread, NULL) != 0)
    return YULC_ERROR_INTERNAL;
  return 0;
}

/* ---------------------------------------------------------------------- */
/* Runtime initialization                                                  */

static pthread_once_t g_init_once = PTHREAD_ONCE_INIT;
static int g_init_status = YULC_ERROR_INTERNAL;

static void *init_worker(void *arg) {
  int *status = (int *)arg;
  lean_initialize_runtime_module();
  lean_object *res =
      initialize_yul_x2devm_x2dcompiler_YulCApi(1, lean_io_mk_world());
  if (lean_io_result_is_ok(res)) {
    lean_dec_ref(res);
    *status = YULC_OK;
  } else {
    lean_io_result_show_error(res);
    lean_dec(res);
    *status = YULC_ERROR_INTERNAL;
  }
  lean_io_mark_end_initialization();
  return NULL;
}

static void init_once(void) {
  int status = YULC_ERROR_INTERNAL;
  if (run_on_big_stack(init_worker, &status) == 0)
    g_init_status = status;
  else
    g_init_status = YULC_ERROR_INTERNAL;
}

int yulc_init(void) {
  pthread_once(&g_init_once, init_once);
  return g_init_status;
}

/* ---------------------------------------------------------------------- */
/* Compilation                                                             */

/* Reject byte sequences lean_mk_string would misinterpret: Lean strings are
 * valid UTF-8 and their runtime length is computed under that assumption. */
static int is_valid_utf8(const unsigned char *s) {
  while (*s) {
    unsigned char c = *s;
    size_t len;
    unsigned int cp;
    if (c < 0x80) {
      s++;
      continue;
    } else if ((c & 0xE0) == 0xC0) {
      len = 1;
      cp = c & 0x1F;
    } else if ((c & 0xF0) == 0xE0) {
      len = 2;
      cp = c & 0x0F;
    } else if ((c & 0xF8) == 0xF0) {
      len = 3;
      cp = c & 0x07;
    } else {
      return 0;
    }
    s++;
    for (size_t i = 0; i < len; i++, s++) {
      if ((*s & 0xC0) != 0x80)
        return 0;
      cp = (cp << 6) | (unsigned int)(*s & 0x3F);
    }
    /* Overlong encodings, surrogates, and out-of-range code points. */
    if ((len == 1 && cp < 0x80) || (len == 2 && cp < 0x800) ||
        (len == 3 && cp < 0x10000) || cp > 0x10FFFF ||
        (cp >= 0xD800 && cp <= 0xDFFF))
      return 0;
  }
  return 1;
}

typedef struct {
  const char *source;
  int status;
  uint8_t *bytecode;
  size_t bytecode_len;
} compile_job;

static void *compile_worker(void *arg) {
  compile_job *job = (compile_job *)arg;
  lean_initialize_thread();
  lean_object *opt = yulc_lean_compile(lean_mk_string(job->source));
  if (lean_is_scalar(opt)) {
    /* Option.none: classify the rejection the way the yulc CLI does. */
    job->status = yulc_lean_parses(lean_mk_string(job->source))
                      ? YULC_ERROR_UNSUPPORTED
                      : YULC_ERROR_PARSE;
  } else {
    /* Option.some bytecode, with the payload a Lean scalar byte array. */
    lean_object *bytes = lean_ctor_get(opt, 0);
    size_t n = lean_sarray_size(bytes);
    uint8_t *buf = (uint8_t *)malloc(n > 0 ? n : 1);
    if (buf == NULL) {
      job->status = YULC_ERROR_INTERNAL;
    } else {
      memcpy(buf, lean_sarray_cptr(bytes), n);
      job->bytecode = buf;
      job->bytecode_len = n;
      job->status = YULC_OK;
    }
    lean_dec(opt);
  }
  lean_finalize_thread();
  return NULL;
}

int yulc_compile(const char *source, uint8_t **bytecode, size_t *bytecode_len) {
  if (bytecode)
    *bytecode = NULL;
  if (bytecode_len)
    *bytecode_len = 0;
  if (source == NULL || bytecode == NULL || bytecode_len == NULL)
    return YULC_ERROR_INTERNAL;
  if (!is_valid_utf8((const unsigned char *)source))
    return YULC_ERROR_INTERNAL;
  int rc = yulc_init();
  if (rc != YULC_OK)
    return rc;
  compile_job job = {source, YULC_ERROR_INTERNAL, NULL, 0};
  if (run_on_big_stack(compile_worker, &job) != 0)
    return YULC_ERROR_INTERNAL;
  if (job.status == YULC_OK) {
    *bytecode = job.bytecode;
    *bytecode_len = job.bytecode_len;
  }
  return job.status;
}

void yulc_free(uint8_t *bytecode) { free(bytecode); }

const char *yulc_status_string(int status) {
  switch (status) {
  case YULC_OK:
    return "success";
  case YULC_ERROR_PARSE:
    return "parse failed";
  case YULC_ERROR_UNSUPPORTED:
    return "parsed, but uses unsupported compiler features";
  case YULC_ERROR_INTERNAL:
    return "internal error (runtime initialization, threading, or invalid "
           "argument)";
  default:
    return "unknown status";
  }
}
