import YulEvmCompilerTests.SolcDifferential
set_option warningAsError true
/-!
# Gas regression baselines over the Solidity Yul corpora

The solc differential already compiles every corpus fixture with both this
compiler and the pinned solc and executes both under the shared scenarios. This
adds a gas dimension on top: for each fixture whose two bytecodes are
behaviorally comparable, we sum the execution gas each spends over the
comparable scenarios and pin *our* total in a per-suite baseline.

CI then fails when this compiler's total rises above its pinned figure. The
corpora track upstream `develop`, so a fixture's *source* can change and move
our gas for reasons unrelated to codegen. solc's pinned total is used as a
content fingerprint to tell the two apart: if solc's total is unchanged the
fixture is unchanged, so a higher `ours` is a real regression; if solc's total
moved, the fixture changed upstream (or solc was bumped) and the entry just
needs re-pinning.
-/

namespace YulEvmCompilerTests.CorpusGas

open EvmSemantics
open YulEvmCompilerTests.SolcDifferential

/-- One pinned fixture: this compiler's and solc's total execution gas summed
over the fixture's gas-comparable scenarios. -/
structure GasRow where
  fixture : String
  ours : Nat
  solc : Nat
  deriving BEq

/-- Total gas each compiler spends over the fixture's gas-comparable scenarios,
or `none` when no scenario is comparable (so there is nothing to pin). -/
def fixtureTotalGas (name : String) (ours solc : ByteArray) : Option (Nat × Nat) :=
  (measureGas ours solc (scenarioSeed := fixtureSeed name)).foldl (init := none)
    fun acc (_, gas) =>
      match gas, acc with
      | none, _ => acc
      | some (o, s), none => some (o, s)
      | some (o, s), some (accOurs, accSolc) => some (accOurs + o, accSolc + s)

inductive Verdict where
  /-- solc's total is unchanged and ours is not above the pin. -/
  | ok
  /-- solc's total is unchanged and ours dropped: re-pin to tighten. -/
  | improved
  /-- solc's total moved: the fixture changed upstream or solc was bumped. -/
  | changed
  /-- solc's total is unchanged and ours rose: a genuine gas regression. -/
  | regression
  deriving BEq

/-- Compare a fresh measurement against its pinned row, using solc's total as a
fingerprint for the fixture's source (see the module comment). -/
def classify (current pinned : GasRow) : Verdict :=
  if current.solc != pinned.solc then .changed
  else if current.ours > pinned.ours then .regression
  else if current.ours < pinned.ours then .improved
  else .ok

def find (rows : Array GasRow) (fixture : String) : Option GasRow :=
  rows.find? (fun row => row.fixture == fixture)

def render (suiteName expectedSolcVersion : String) (rows : Array GasRow) : String :=
  let sorted := rows.qsort (fun a b => a.fixture < b.fixture)
  let header := #[
    s!"# Total execution gas of this compiler's bytecode vs solc's for {suiteName}.",
    "# Generated by scripts/UpdateCorpusGas.lean; re-pin with scripts/update-gas.sh.",
    s!"# Pinned to solc {expectedSolcVersion}, EVM version osaka. 'ours' is a ceiling:",
    "# CI fails if this compiler's total rises above it while solc's is unchanged.",
    "# columns: fixture<TAB>ours<TAB>solc"
  ]
  let body := sorted.map fun row => s!"{row.fixture}\t{row.ours}\t{row.solc}"
  String.intercalate "\n" (header ++ body).toList ++ "\n"

def parse (contents : String) : Except String (Array GasRow) := do
  let mut rows := #[]
  for rawLine in contents.splitOn "\n" do
    let line := rawLine.trimAscii.copy
    if line.isEmpty || line.startsWith "#" then continue
    match line.splitOn "\t" with
    | [fixture, ours, solc] =>
        match ours.toNat?, solc.toNat? with
        | some ours, some solc => rows := rows.push { fixture, ours, solc }
        | _, _ => throw s!"malformed gas figures: {line}"
    | _ => throw s!"malformed gas baseline row: {line}"
  return rows

/-- Read a gas baseline file, tolerating absence (an empty baseline pins
nothing, so every comparable fixture is simply reported as unpinned). -/
def readBaseline (path : System.FilePath) : IO (Except String (Array GasRow)) := do
  if ← path.pathExists then
    return parse (← IO.FS.readFile path)
  else
    return .ok #[]

end YulEvmCompilerTests.CorpusGas
