import YulParser.Compile
import YulEvmCompilerTests.Solc
import YulEvmCompilerTests.SolcDifferential
import YulEvmCompilerTests.SolidityCorpus

/-!
Tier A gas comparison: a small, hand-written, in-repo benchmark suite whose
exact execution gas is pinned in a checked-in baseline.

Every fixture in the benchmark directory must compile with *both* this compiler
and the pinned solc, and each generated bytecode is run under the shared set of
deterministic scenarios (`YulEvmCompilerTests.SolcDifferential.scenarios`). For
every scenario where the two programs reach identical observable behavior, the
gas each spends is recorded; behavior is compared exactly, gas is not.

Because gas is a deterministic function of (bytecode, scenario) and both the
solc version and EVM fork are pinned, the numbers are fully reproducible in CI.
The default mode regenerates the baseline in memory and fails if it differs from
the committed file — so any change in our codegen, or a solc bump, must be
acknowledged by re-pinning with `scripts/update-gas.sh` and reviewing the diff.
`--update` rewrites the baseline in place.
-/

open System YulParser
open EvmSemantics
open YulEvmCompilerTests.Solc
open YulEvmCompilerTests.SolcDifferential
open YulEvmCompilerTests.SolidityCorpus

/-- Integer overhead of our gas over solc's, in percent, for display only.
100 means parity; a non-optimizing compiler is expected to exceed it. -/
private def overheadPercent (ours solc : Nat) : Nat :=
  if solc == 0 then 0 else ours * 100 / solc

private structure Row where
  fixture : String
  scenario : String
  gas : Option (Nat × Nat)

/-- Compile one benchmark with both compilers and measure per-scenario gas.
Both compilers must accept the source: a curated benchmark that either compiler
rejects is a bug in the suite, not a tolerated difference. -/
private def measureFixture
    (solcPath name source : String) : IO (Except String (Array Row)) := do
  match compileSource source with
  | none => return .error "this compiler rejected the benchmark"
  | some ours =>
      match ← compileWithSolc solcPath source with
      | .error message => return .error message
      | .ok solc =>
          let measured := measureGas ours solc (scenarioSeed := fixtureSeed name)
          return .ok (measured.map fun (scenario, gas) => { fixture := name, scenario, gas })

private def renderBaseline (expectedSolcVersion : String) (rows : Array Row) : String :=
  let header := #[
    "# Execution gas of this compiler's bytecode vs solc's, per benchmark and scenario.",
    "# Generated by scripts/CheckGasBenchmarks.lean; re-pin with scripts/update-gas.sh.",
    s!"# Pinned to solc {expectedSolcVersion}, EVM version osaka. Behavior is checked",
    "# exactly elsewhere; these numbers are a measurement, not an equality target.",
    "# columns: fixture<TAB>scenario<TAB>ours<TAB>solc  (or 'skipped' when not comparable)"
  ]
  let body := rows.map fun row =>
    match row.gas with
    | some (ours, solc) => s!"{row.fixture}\t{row.scenario}\t{ours}\t{solc}"
    | none => s!"{row.fixture}\t{row.scenario}\tskipped"
  String.intercalate "\n" (header ++ body).toList ++ "\n"

private def printSummary (rows : Array Row) : IO Unit := do
  IO.println "Gas benchmark summary (ours vs solc, overhead = ours/solc):"
  for row in rows do
    match row.gas with
    | some (ours, solc) =>
        IO.println s!"  {row.fixture} [{row.scenario}]: {ours} vs {solc} ({overheadPercent ours solc}%)"
    | none =>
        IO.println s!"  {row.fixture} [{row.scenario}]: skipped (not behaviorally comparable)"

private def usage : String :=
  "usage: CheckGasBenchmarks <benchmark-dir> <baseline-file> " ++
    "<solc-path> <expected-solc-version> [--update]"

private def run
    (benchmarkDir baselineFile : FilePath)
    (solcPath expectedSolcVersion : String) (update : Bool) : IO UInt32 := do
  match ← checkSolcVersion solcPath expectedSolcVersion with
  | .error message => IO.eprintln message; return 1
  | .ok () => pure ()
  let paths ← benchmarkDir.walkDir
  let files := paths.filter (fun path => path.extension == some "yul")
    |>.qsort (fun a b => relativeName benchmarkDir a < relativeName benchmarkDir b)
  if files.isEmpty then
    IO.eprintln s!"{benchmarkDir}: found no .yul benchmarks"
    return 1
  let mut rows : Array Row := #[]
  let mut errors : Array (String × String) := #[]
  for path in files do
    let name := relativeName benchmarkDir path
    let source := fixtureSource (← IO.FS.readFile path)
    match ← measureFixture solcPath name source with
    | .ok fixtureRows => rows := rows ++ fixtureRows
    | .error message => errors := errors.push (name, message)
  printSummary rows
  unless errors.isEmpty do
    printNames "Benchmarks that failed to compile on both toolchains:" (errors.map (·.1))
    for (name, message) in errors do IO.eprintln s!"  {name}: {message}"
    return 1
  let generated := renderBaseline expectedSolcVersion rows
  if update then
    IO.FS.writeFile baselineFile generated
    IO.println s!"Wrote {rows.size} gas rows to {baselineFile}."
    return 0
  unless ← baselineFile.pathExists do
    IO.eprintln s!"{baselineFile}: missing; run scripts/update-gas.sh to create it"
    return 1
  let committed ← IO.FS.readFile baselineFile
  if committed == generated then
    IO.println s!"Gas baseline up to date ({rows.size} rows)."
    return 0
  IO.eprintln s!"Gas baseline is stale. Re-pin with scripts/update-gas.sh and review the diff."
  IO.eprintln "--- committed"
  IO.eprintln committed
  IO.eprintln "+++ regenerated"
  IO.eprintln generated
  return 1

def main (args : List String) : IO UInt32 :=
  match args with
  | [benchmarkDir, baselineFile, solcPath, expectedSolcVersion] =>
      run benchmarkDir baselineFile solcPath expectedSolcVersion false
  | [benchmarkDir, baselineFile, solcPath, expectedSolcVersion, "--update"] =>
      run benchmarkDir baselineFile solcPath expectedSolcVersion true
  | _ => do IO.eprintln usage; return 64
